{
 "title": "Zencash API",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Log volumes",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 6 },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({app=\"zencash-api\"}[$__interval]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "x": 0, "y": 6, "w": 4, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"zencash-api\", level=\"error\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "stat",
   "gridPos": { "x": 4, "y": 6, "w": 4, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"zencash-api\", level=\"warn\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Info",
   "type": "stat",
   "gridPos": { "x": 8, "y": 6, "w": 4, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"zencash-api\", level=\"info\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Real time logs",
   "type": "logs",
   "gridPos": { "x": 0, "y": 10, "w": 24, "h": 14 },
   "targets": [
    {
     "expr": "{app=\"zencash-api\"}"
    }
   ]
  },
  {
   "title": "Only errors",
   "type": "logs",
   "gridPos": { "x": 0, "y": 24, "w": 24, "h": 10 },
   "targets": [
    {
     "expr": "{app=\"zencash-api\", level=\"error\"}"
    }
   ]
  }
 ]
}